ADD Mikaila Shanin Sotaso
psub-bsit3b-ccit106-2023/quizpocalypse pull request #20
Opened 2023-02-07 02:35 UTC by MikailaShaninSotaso

2023-02-08 11:24 UTC, kulotsystems requested changes

2023-02-08 11:24 UTC, kulotsystems commented on js/modules/mikailashanin.js
> +            username: "MikailaShaninSotaso",
Please update your GitHub username.

```suggestion
            username: "miksdumb",
```

2023-02-08 13:43 UTC, miksdumb reviewed
Sir, can u check it out again please.

2023-02-08 14:26 UTC, kulotsystems requested changes

2023-02-08 14:26 UTC, kulotsystems commented on js/store.js
> +import miksdumb from './modules/miksdumb.js';
You only changed your GitHub username but you did not rename your module. So, you can keep your previous module file name.

```suggestion
import miksdumb from './modules/mikailashanin.js';
```

2023-02-08 17:59 UTC, kulotsystems commented
Please also delete the following:
- `node_modules` folder
- `package-lock.json` file
- `package.json` file

2023-02-09 01:27 UTC, kulotsystems requested changes
Thanks @miksdumb!

Lastly, please also delete the following:
- `node_modules` folder
- `package-lock.json` file
- `package.json` file

Thank you!

2023-02-09 15:24 UTC, merged